<div class="text-center">
    <h1>Novo Post</h1>
    <?php
       $form = $this->form;
        $form->setAttribute('action', $this->url());
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get("id"));
    ?>
    <div class="form-group">
        <?= $this->formText($form->get("title")); ?>
    </div>
    <div class="form-group">
        <?= $this->formText($form->get("text")); ?>
    </div>
    <?php
        echo $this->formSubmit($form->get("submit"));
        echo $this->form()->closeTag();
    ?>
    <hr>
    <a class="btn btn-info" href="/blog"><i class="fa-solid fa-arrow-left"></i></a>
</div>